//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.Types.Fido2.Scalars {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScalarResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScalarResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HotChocolate.Types.Fido2.Scalars.ScalarResources", typeof(ScalarResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AuthenticationExtensionsClientInputsType_Description {
            get {
                return ResourceManager.GetString("AuthenticationExtensionsClientInputsType_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticationExtensionsClientOutputsType_Description {
            get {
                return ResourceManager.GetString("AuthenticationExtensionsClientOutputsType_Description", resourceCulture);
            }
        }
        
        internal static string Base64UrlType_Description {
            get {
                return ResourceManager.GetString("Base64UrlType_Description", resourceCulture);
            }
        }
        
        internal static string Base64UrlType_IsInvalid_ParseLiteral {
            get {
                return ResourceManager.GetString("Base64UrlType_IsInvalid_ParseLiteral", resourceCulture);
            }
        }
        
        internal static string Base64UrlType_IsInvalid_ParseValue {
            get {
                return ResourceManager.GetString("Base64UrlType_IsInvalid_ParseValue", resourceCulture);
            }
        }
        
        internal static string EnumMemberType_WebAuthn_Description {
            get {
                return ResourceManager.GetString("EnumMemberType_WebAuthn_Description", resourceCulture);
            }
        }
        
        internal static string EnumMemberType_IsInvalid_ParseLiteral {
            get {
                return ResourceManager.GetString("EnumMemberType_IsInvalid_ParseLiteral", resourceCulture);
            }
        }
        
        internal static string EnumMemberType_IsInvalid_ParseValue {
            get {
                return ResourceManager.GetString("EnumMemberType_IsInvalid_ParseValue", resourceCulture);
            }
        }
        
        internal static string TypedDictionaryType_IsInvalid_ParseLiteral {
            get {
                return ResourceManager.GetString("TypedDictionaryType_IsInvalid_ParseLiteral", resourceCulture);
            }
        }
        
        internal static string TypedDictionaryType_IsInvalid_ParseValue {
            get {
                return ResourceManager.GetString("TypedDictionaryType_IsInvalid_ParseValue", resourceCulture);
            }
        }
    }
}
