//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotChocolate.Types.Fido2 {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjectTypeResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjectTypeResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HotChocolate.Types.Fido2.ObjectTypeResources", typeof(ObjectTypeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AssertionVerificationResultType_Description {
            get {
                return ResourceManager.GetString("AssertionVerificationResultType_Description", resourceCulture);
            }
        }
        
        internal static string AttestationConveyancePreferenceType_Description {
            get {
                return ResourceManager.GetString("AttestationConveyancePreferenceType_Description", resourceCulture);
            }
        }
        
        internal static string AttestationConveyancePreferenceType_Direct_Description {
            get {
                return ResourceManager.GetString("AttestationConveyancePreferenceType_Direct_Description", resourceCulture);
            }
        }
        
        internal static string AttestationConveyancePreferenceType_Indirect_Description {
            get {
                return ResourceManager.GetString("AttestationConveyancePreferenceType_Indirect_Description", resourceCulture);
            }
        }
        
        internal static string AttestationConveyancePreferenceType_None_Description {
            get {
                return ResourceManager.GetString("AttestationConveyancePreferenceType_None_Description", resourceCulture);
            }
        }
        
        internal static string AttestationVerificationSuccessType_Description {
            get {
                return ResourceManager.GetString("AttestationVerificationSuccessType_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAssertionResponseInputType_AuthenticatorData_Description {
            get {
                return ResourceManager.GetString("AuthenticatorAssertionResponseInputType_AuthenticatorData_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAssertionResponseInputType_ClientDataJson_Description {
            get {
                return ResourceManager.GetString("AuthenticatorAssertionResponseInputType_ClientDataJson_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAssertionResponseInputType_Description {
            get {
                return ResourceManager.GetString("AuthenticatorAssertionResponseInputType_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAssertionResponseInputType_Signature_Description {
            get {
                return ResourceManager.GetString("AuthenticatorAssertionResponseInputType_Signature_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAssertionResponseInputType_UserHandle_Description {
            get {
                return ResourceManager.GetString("AuthenticatorAssertionResponseInputType_UserHandle_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAttestationResponseInputType_AttestationObject_Description {
            get {
                return ResourceManager.GetString("AuthenticatorAttestationResponseInputType_AttestationObject_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAttestationResponseInputType_ClientDataJson_Description {
            get {
                return ResourceManager.GetString("AuthenticatorAttestationResponseInputType_ClientDataJson_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAttestationResponseInputType_Description {
            get {
                return ResourceManager.GetString("AuthenticatorAttestationResponseInputType_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAttachmentType_CrossPlatform_Description {
            get {
                return ResourceManager.GetString("AuthenticatorAttachmentType_CrossPlatform_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAttachmentType_Description {
            get {
                return ResourceManager.GetString("AuthenticatorAttachmentType_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorAttachmentType_Platform_Description {
            get {
                return ResourceManager.GetString("AuthenticatorAttachmentType_Platform_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorSelectionCriteriaType_AuthenticatorAttachment_Description {
            get {
                return ResourceManager.GetString("AuthenticatorSelectionCriteriaType_AuthenticatorAttachment_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorSelectionCriteriaType_Description {
            get {
                return ResourceManager.GetString("AuthenticatorSelectionCriteriaType_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorSelectionCriteriaType_RequireResidentKey_Description {
            get {
                return ResourceManager.GetString("AuthenticatorSelectionCriteriaType_RequireResidentKey_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorSelectionCriteriaType_UserVerification_Description {
            get {
                return ResourceManager.GetString("AuthenticatorSelectionCriteriaType_UserVerification_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorTransportType_Ble_Description {
            get {
                return ResourceManager.GetString("AuthenticatorTransportType_Ble_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorTransportType_Description {
            get {
                return ResourceManager.GetString("AuthenticatorTransportType_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorTransportType_Internal_Description {
            get {
                return ResourceManager.GetString("AuthenticatorTransportType_Internal_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorTransportType_Nfc_Description {
            get {
                return ResourceManager.GetString("AuthenticatorTransportType_Nfc_Description", resourceCulture);
            }
        }
        
        internal static string AuthenticatorTransportType_Usb_Description {
            get {
                return ResourceManager.GetString("AuthenticatorTransportType_Usb_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAssertionInputType_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAssertionInputType_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAssertionInputType_Extensions_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAssertionInputType_Extensions_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAssertionInputType_Id_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAssertionInputType_Id_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAssertionInputType_RawId_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAssertionInputType_RawId_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAssertionInputType_Response_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAssertionInputType_Response_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAssertionInputType_Type_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAssertionInputType_Type_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAttestationInputType_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAttestationInputType_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAttestationInputType_Extensions_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAttestationInputType_Extensions_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAttestationInputType_Id_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAttestationInputType_Id_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAttestationInputType_RawId_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAttestationInputType_RawId_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAttestationInputType_Response_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAttestationInputType_Response_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialAttestationInputType_Type_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialAttestationInputType_Type_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialCreationOptionsType_Attestation_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialCreationOptionsType_Attestation_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialCreationOptionsType_AuthenticatorSelection_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialCreationOptionsType_AuthenticatorSelection_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialCreationOptionsType_Challenge_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialCreationOptionsType_Challenge_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialCreationOptionsType_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialCreationOptionsType_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialCreationOptionsType_ExcludeCredentials_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialCreationOptionsType_ExcludeCredentials_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialCreationOptionsType_Extensions_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialCreationOptionsType_Extensions_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialCreationOptionsType_PubKeyCredParams_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialCreationOptionsType_PubKeyCredParams_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialCreationOptionsType_Rp_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialCreationOptionsType_Rp_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialCreationOptionsType_Timeout_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialCreationOptionsType_Timeout_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialCreationOptionsType_User_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialCreationOptionsType_User_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialDescriptorType_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialDescriptorType_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialDescriptorType_Id_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialDescriptorType_Id_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialDescriptorType_Transports_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialDescriptorType_Transports_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialDescriptorType_Type_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialDescriptorType_Type_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialParametersType_Alg_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialParametersType_Alg_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialParametersType_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialParametersType_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialParametersType_Type_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialParametersType_Type_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialRequestOptionsType_AllowCredentials_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialRequestOptionsType_AllowCredentials_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialRequestOptionsType_Challenge_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialRequestOptionsType_Challenge_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialRequestOptionsType_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialRequestOptionsType_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialRequestOptionsType_Extensions_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialRequestOptionsType_Extensions_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialRequestOptionsType_RpId_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialRequestOptionsType_RpId_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialRequestOptionsType_Timeout_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialRequestOptionsType_Timeout_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialRequestOptionsType_UserVerification_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialRequestOptionsType_UserVerification_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialRpEntityType_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialRpEntityType_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialRpEntityType_Id_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialRpEntityType_Id_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialRpEntityType_Name_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialRpEntityType_Name_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialTypeType_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialTypeType_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialTypeType_PublicKey_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialTypeType_PublicKey_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialUserEntityType_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialUserEntityType_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialUserEntityType_DisplayName_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialUserEntityType_DisplayName_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialUserEntityType_Id_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialUserEntityType_Id_Description", resourceCulture);
            }
        }
        
        internal static string PublicKeyCredentialUserEntityType_Name_Description {
            get {
                return ResourceManager.GetString("PublicKeyCredentialUserEntityType_Name_Description", resourceCulture);
            }
        }
        
        internal static string UserVerificationRequirementType_Description {
            get {
                return ResourceManager.GetString("UserVerificationRequirementType_Description", resourceCulture);
            }
        }
        
        internal static string UserVerificationRequirementType_Discouraged_Description {
            get {
                return ResourceManager.GetString("UserVerificationRequirementType_Discouraged_Description", resourceCulture);
            }
        }
        
        internal static string UserVerificationRequirementType_Preferred_Description {
            get {
                return ResourceManager.GetString("UserVerificationRequirementType_Preferred_Description", resourceCulture);
            }
        }
        
        internal static string UserVerificationRequirementType_Required_Description {
            get {
                return ResourceManager.GetString("UserVerificationRequirementType_Required_Description", resourceCulture);
            }
        }
    }
}
